version: '3.8'

services:
  server:
    build: .
    working_dir: /app
    ports:
      - 8002:3000
    networks:
      - database
    env_file:
      - .env
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - |
        diesel migration run
        /usr/local/bin/myapp

networks:
  database:
    external: true
