-- Your SQL goes here
-- generated by https://dbdiagram.io/d/5ea2fc4f39d18f5553fe2936
CREATE TABLE `tweets` (
  `id` VARCHAR(36) PRIMARY KEY, -- UUID
  `tweet_id` VARCHAR(64),
  `comment` VARCHAR(10000) NOT NULL -- 適当
);

CREATE TABLE `tags` (
  `id` VARCHAR(36) PRIMARY KEY, -- UUID
  `tag` VARCHAR(255) NOT NULL
);

CREATE TABLE `tweets_to_tags` (
  `id` VARCHAR(36) PRIMARY KEY, -- UUID
  `tweets_id` VARCHAR(36) NOT NULL,
  `tags_id` VARCHAR(36) NOT NULL
);

ALTER TABLE `tweets_to_tags` ADD FOREIGN KEY (`tweets_id`) REFERENCES `tweets` (`id`);

ALTER TABLE `tweets_to_tags` ADD FOREIGN KEY (`tags_id`) REFERENCES `tags` (`id`);

CREATE UNIQUE INDEX `tweets_index_0` ON `tweets` (`tweet_id`);

CREATE UNIQUE INDEX `tags_index_1` ON `tags` (`tag`);
