name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306

    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1/test"
      RUST_LOG: debug

    steps:
      - uses: actions/checkout@v1
      - name: Setup
        working-directory: ./server
        run: |
          sudo /etc/init.d/mysql start
          sudo apt update
          sudo apt install -y libmysqlclient-dev libsqlite3-dev
          cargo install diesel_cli --no-default-features --features "mysql sqlite"
          diesel setup
          diesel migration run
      - name: Build
        working-directory: ./server
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./server
        run: cargo test --verbose
